### ISSUE TITLE
[Idea] Showing more columns in the main table?

### ISSUE THREAD

**Issue by The-Gig** [torhus/monster-browser#4] opened 2022-07-21 10:32 UTC
Just an idea, what about adding a few more columns to the main table? I was thinking about **gamename** and **gametype** (the numerical one).
It looks like Tremulous doesn't broadcast a "gametype" info, but in that case I guess leaving the field empty should be enough.

**Comment by torhus** [comment] 2022-07-21 15:38
The problem is that what you would want depends on the game. Tremulous differs too much from Q3 here. `gametype` is shown in the Game column, though.

**Comment by The-Gig** [comment] 2022-07-21 16:16
About the "game" column, I thought it was showing the "game" info from serverinfo string, but it looks like it's not the case (so the actual "game" variable could be nice to be shown, too). It looks like it shows the gametype number for high number, and a short text description for the original Q3A gametypes (1v1, TDM, FFA, CTF). Is the conversion of those low numbers hardcoded somewhere? Some mods may be so different than the basegame that those descriptions may not fit... a little number probably, but possible.

I don't get how the program knows that in Smoking Guns gametype 5 is "BR" or in World of Padman gametype 4 is "LPS"... Considering in mods.ini you may write _anything_ in section name, how does it know which game actually each section is referring to?

**Comment by torhus** [comment] 2022-07-21 16:49
It's based on the value of `mod`. It's hardcoded, which it probably shouldn't have been, except for the Q3 defaults. But it shouldn't be to hard to fix, I'll see if I can get it done.

https://github.com/torhus/monster-browser/blob/master/src/serverdata.d#L200

**Comment by The-Gig** [comment] 2022-08-24 12:20
It's good enanchement that now the short description for gametype is customizable (https://github.com/torhus/monster-browser/issues/10), very well!

Anyway, I still think that adding separate colums for "game" and "gamename" variables, while renaming the current "game" one (to gametype, gt, mode or something similar), could be useful.

**Comment by The-Gig** [comment] 2022-09-05 09:36
Hi! I tried the new version 0.9e. Very well, but with the addition of "Quake III (all servers)" entry (and in general the ability to show "all servers" for a game without having to filter for a certain mod as before), I really think adding colums for _game_ and _gamename_ cvars would be an _extremely_ useful feature.

**Comment by torhus** [comment] 2022-09-05 13:14
I'm a bit worried that having Game type, Game, and Gamename columns would be confusing to many people. Maybe the better solution is to add a more flexible filter selector, but that's a bigger project.

**Comment by The-Gig** [comment] 2022-10-17 20:13
As the program is keeping getting better and better with the new releases, I'd still like to be able to see game and gamename columns... If you still think it's a feature for advanced users, why don't add a checkbox in options menu to show them?

**Comment by torhus** [comment] 2022-10-18 22:04
Is the idea of having those extra columns to make it easier to adjust mods.ini? I did a quick test version with this in it. So far it's not configurable, and a bit buggy (don't try to sort on those columns): https://ci.appveyor.com/project/torhus/monster-browser/builds/45110848/artifacts

Why would you need to see the gametype number, by the way?

**Comment by The-Gig** [comment] 2022-10-19 07:48
The reasons for those columns are:
- Quickly finding out whether a server is running the base game or a mod, and which mod.
- Helping learning about the existence of those cvars.
- Helping figuring out why a certain server popped out from your search term in the search field, when it's not part of the server name.
- Helping to find out what you have to type when customizing mods.ini.
I'm just a little unsure whether [gamename] should be enabled by default or it should be an option, for experienced users, as some games have is set poorly which is misleading (e.g. many OA servers show "quake3arena" there, despite actually being OpenArena servers... I guess due to using ioquake3 binaries instead of official oa binaries)...
![immagine](https://user-images.githubusercontent.com/23258514/196625954-be06e7cc-81a1-4b9b-b4db-0a49ba2ee411.png)
But on the other hand, seeing both fields all the time can allow users to find out why some servers running "osp" mod showed up when they searched for "baseq3" instead.
![immagine](https://user-images.githubusercontent.com/23258514/196625709-ccf4c61b-287d-4cf8-8984-fac852249ce3.png)

About allowing to see the gametype as a number was just a thought thinking about the fact that mods gametypes may differ from basegame gametypes, hence in some situations the description could be misleading. As example, OpenArena has got 12 gametypes (13 if you count the yet unreleased Possession mode), but servers running OA might be running mods based upon quake3 gamecode, so they might have added their own gametypes, so in a certain mod, gametype 5 could be something else than Oneflag, which was something initialy added by Team Arena mod (and a few mods might even have replaced the first 4 gametypes).

On a side note, I guess I'll have to point out in OA github that probably the binary should set "game" to "openarena" instead of "baseoa".

**Comment by torhus** [comment] 2022-10-23 21:08
The work on this is still unfinished, but you can get a 0.9g build with the extra columns added here:
https://ci.appveyor.com/project/torhus/monster-browser/builds/45156480/artifacts

**Comment by The-Gig** [comment] 2022-10-24 07:43
Tried, nice! Looking forward for when ordering for them will not crash the program anymore. :-)

**Comment by torhus** [comment] 2022-10-28 19:59
Partially fixed in v0.9h. The game type is still only available in the Cvar table.

**Comment by The-Gig** [comment] 2022-10-31 09:15
0.9h tested. Good, thank you!
Maybe "game" column might have been shown by default, anyway the ability to enable it is the important thing!

**Comment by The-Gig** [comment] 2022-10-31 11:12
> On a side note, I guess I'll have to point out in OA github that probably the binary should set "game" to "openarena" instead of "baseoa".

Ehm... I was trying to find out if that might have been a good idea, but I discovered a big _rabbit hole_ which frightens me... I try to sum up what I found out so far.
- Other than [gamename], also a [com_gamename] cvar exists, and in some cases the two may not have the same value.
- Qtracker "mod" column does not seem to read the [game] cvar like MonsterBrowser does. It looks like it reads [gamename] instead (which seems to be much more "used/customized" to show the mod name in Quake3 servers than it is in OpenArena servers, I don't know how).
- Depending from _how_ you query the server, you get some cvars/values instead of others. !!!! (Continue reading)
- Using in-game /serverstatus command, or Qtracker, it looks like you get no [game] cvar at all, while [gamename] _may or may not_ be the same value you get using Qstat/MonsterBrowser.
- Using _oaquery_ script (<https://github.com/rdntcntrl/oaquery>) with the options like in this screenshot 
![immagine](https://user-images.githubusercontent.com/23258514/198993708-f5d872c1-cce7-448d-a4f6-e0440cab348a.png)
You can see that it splits the output into "info variables" and "status variables". I did not know about this difference. You can notice that there are _two_ [gamename] cvars (one info and one status kind), which can hold different values. And that [game] is only in "info" section. I wonder whether there is a way to get the [game] info from within the game...

**Comment by torhus** [comment] 2022-10-31 14:54
I'm guessing that the "Info Variables" (getinfo query response) is what is used in the in-game server browser, while "Status Variables" (getstatus query response) is used when you connect. It seems strange that they would conflict, maybe it's a bug?

**Comment by torhus** [comment] 2022-12-12 22:00
@The-Gig I'm thinking about adding a setting to enable a numerical game type column, I suppose that would mean I can close this issue?

**Comment by The-Gig** [comment] 2022-12-13 08:14
I guess so... :-)

**Comment by torhus** [comment] 2022-12-15 21:46
I added the column, maybe I'll try to fix one or two bugs and make a release tomorrow...

https://ci.appveyor.com/project/torhus/monster-browser/builds/45697318/artifacts

**Comment by The-Gig** [comment] 2022-12-16 10:47
Nice! I wonder whether it's better "Numerical GT", "Gametype N" or "[g_gametype]", as column header...

**Comment by torhus** [comment] 2022-12-16 15:39
> Nice! I wonder whether it's better "Numerical GT", "Gametype N" or "[g_gametype]", as column header...

I set it to [g_gametype] first, but the value is actually taken from the gametype, so it seemed wrong to call it that. I thought it should start with something else than "Game", to differentiate from the other Game type column. Make sense?

**Comment by The-Gig** [comment] 2022-12-16 15:47
I don't think there is need to start with something else than "game"...
Couldn't you just take the value from g_gametype and call it a day?

**Comment by torhus** [comment] 2022-12-16 16:39
I suppose I could call it "Game type #"k, how about that?

**Comment by torhus** [comment] 2022-12-16 17:25
The downside is they will look the same in practice, except for the contents:
![MB_Gametype](https://user-images.githubusercontent.com/19881605/208154096-8649a07d-68c8-4d7c-84d7-c8716db560d7.png)

**Closed** 2022-12-16 19:51 UTC
Labels: enhancement

**Comment by The-Gig** [comment] 2022-12-17 18:48
> The downside is they will look the same in practice, except for the contents: ![MB_Gametype](https://user-images.githubusercontent.com/19881605/208154096-8649a07d-68c8-4d7c-84d7-c8716db560d7.png)

Probably not a big issue, I guess...
